language: php
php:
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - wget http://pecl.php.net/get/yaml-1.1.1.tgz
  - tar -xzf yaml-1.1.1.tgz
  - sh -c "cd yaml-1.1.1 && phpize && ./configure && sudo make install"
  - echo "extension=yaml.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p coverage
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
